set number
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set hidden

syntax on

"fix backspace
set bs=2

if has('gui_running')
    colorscheme desert
endif

set undodir=~/.vim/undo//
set backupdir=~/.vim/backup//
set directory=~/.vim/swp//
